### ISSUE TITLE
can you do at least install in visual studio?

### ISSUE THREAD

**Issue by ghost** [JackTrapper/Delphi-for-Visual-Studio#1]
I've been beating my head for days and not only can I compile it in the visual, but I don't know how to install it so I can start testing something

**Comment by JackTrapper** [comment]
I only cloned the dead project from CodeProject to ensure it continues to exist. I could never get it working in any way either.

Fortunately with open source, anyone else can try to make it work!

**Comment by ghost** [comment]
I did it, it works and I didn't need to change anything, I didn't know how to install it in Visual Studio, but now I see that it's simple, I'm even making improvements, thanks
